language: python
python:
  - "3.6"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'

install: "pip3 install -r requirements.txt"

script: nosetests

after_success:
 - codecov
