language: python
python:
  - "3.6"

services:
  - mysql

# command to install dependencies
install: "pip3 install -r requirements.txt"

env:
  global:
  - DATABASE_URI='mysql+pymysql://root:root@localhost:3306/test'

before_script:
  - mysql -c 'create database testdb;' -U mysql

# command to run tests
script: nosetests

after_success:
 - codecov

