language: python
python:
  - "3.6"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'

install: "pip3 install -r requirements.txt"

env:
  global:
    - DATABASE_URI='mysql+pymysql://root:root@localhost:3306/test'

script: nosetests

after_success:
 - codecov
